language:   r
sudo:   false
cache:  packages

warnings_are_errors: false

os:
    - linux

env:
  - CPLEX_HOME="$HOME/lib"
  - JDK=openjdk11


before_install:
    - echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
    - chmod 600 ~/.netrc
    - jdk_switcher use $JDK
    - git clone https://github.com/ctlab/private-libraries.git lib


r_packages:
    - covr   
  

after_success:
      - Rscript -e 'library(covr); codecov()'
